version: '3.8'

services:
  redis:
    image: "redis:7-alpine"
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  app:
    image: simple:0.0.1-SNAPSHOT  # Use the image you built
    container_name: spring-native-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - BPL_JVM_THREAD_COUNT=50  # Optional, helps with low memory
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
